### ISSUE TITLE
Rename MarginLoss to AgreementLoss?

### ISSUE THREAD

**Issue by joshday** [JuliaML/Losses.jl#24]
Similar to how `value`, `deriv`, etc. are a function of the distance (residual) for DistanceLoss, how about changing MarginLoss to AgreementLoss, as those methods are a function of the agreement?

**Comment by Evizero** [comment]
While I see the argument, I don't really want to digress too much from the actual theory behind it for no reason. especially if it is not one of those cases where different fields have different names.

**Comment by Evizero** [comment]
That said, I am open to put it on a vote if you feel strongly about this

**Comment by joshday** [comment]
I don't feel strongly, just thought I'd bring it up while we're hashing out what to call things.
