### ISSUE TITLE
Potential conflict with `Base.LinAlg`

### ISSUE THREAD

**Issue by ahwillia** [JuliaML/Losses.jl#30]
Is this anything to be worried about?

```julia
julia> module X
       using Losses
       using Base.LinAlg
       
       # errors because ambiguous
       issymmetric(L2DistLoss())
       end
WARNING: both LinAlg and Losses export "issymmetric"; uses of it in module X must be qualified
ERROR: UndefVarError: issymmetric not defined
```

**Comment by tbreloff** [comment]
Yes... We should be doing Base.issymmetric

**Comment by Evizero** [comment]
Yes! no brainer. Did not know about it

**Comment by Evizero** [comment]
I'll leave this upon to remember that I still have to `import Base.LinAlg.issymmetric` in Losses.

**Comment by ahwillia** [comment]
You can actually do `Base.issymmerric` directly.

**Comment by Evizero** [comment]
This is new in 0.5, right? in 0.4 I am only finding `issym`

**Comment by ahwillia** [comment]
Correct. I didn't realize this.


On Mon, Aug 15, 2016 at 12:43 AM, Christof Stocker <notifications@github.com

**Comment by Evizero** [comment]
should be fixed
