### ISSUE TITLE
Consider tests against ArrayFire.jl

### ISSUE THREAD

**Issue by Evizero** [JuliaML/Losses.jl#32]
https://github.com/JuliaComputing/ArrayFire.jl

Worth thinking about given that it has a CPU back-end that should work on travis. In the end we would like to run these things on the GPU.

Thoughts?

**Comment by Evizero** [comment]
Looking into this a bit I don't think Losses will lend themself to that so well. I think the most benefit would be for transformations if we do them cleverly. I will look into it a in a bit more detail further down the road, right now this has a lower priority for me

**Comment by tbreloff** [comment]
Agreed. This is a job for transformations
