### ISSUE TITLE
Repo needs a find/replace for stricktly -> strictly

### ISSUE THREAD

**Issue by joshday** [JuliaML/Losses.jl#45]
I noticed the misspelling in some doc strings.

**Comment by Evizero** [comment]
I feel like I should point out again that I am a native German speaker and blameless for my ignorance 🌝 .

No, but seriously, thanks for pointing that out. I legitimately thought this was the right way to spell it and did not double check.

**Comment by joshday** [comment]
No worries.  If I had to spell German words it would turn out much worse.
